import { run } from "@ai-hero/sandcastle";
import { docker } from "@ai-hero/sandcastle/sandboxes/docker";
import { writeFileSync } from "fs";
import { join } from "path";
import { createRequire } from "module";

const require = createRequire(import.meta.url);

const scriptPath = join(process.cwd(), ".sandcastle", "minimax-agent.cjs");
const scriptContent = [
  '"use strict";',
  "const { OpenAI } = require(\"openai\");",
  "const { spawn } = require(\"child_process\");",
  "const apiKey = process.env.MINIMAX_API_KEY;",
  "const baseURL = process.env.MINIMAX_BASE_URL || \"https://api.minimax.io/v1\";",
  "const model = process.env.MODEL || \"MiniMax-Text-01\";",
  "if (!apiKey) { console.error(\"MINIMAX_API_KEY not set\"); process.exit(1); }",
  "const client = new OpenAI({ apiKey, baseURL });",
  "function runShell(cmd) {",
  "  return new Promise((resolve) => {",
  "    const child = spawn(\"/bin/bash\", [\"-c\", cmd], { cwd: process.cwd(), timeout: 30000 });",
  "    let stdout = \"\", stderr = \"\";",
  "    child.stdout.on(\"data\", d => stdout += d);",
  "    child.stderr.on(\"data\", d => stderr += d);",
  "    child.on(\"close\", code => resolve({ stdout: stdout.slice(0,10000), stderr: stderr.slice(0,3000), code }));",
  "    child.on(\"error\", err => resolve({ stdout: \"\", stderr: err.message, code: 1 }));",
  "  });",
  "}",
  "function writeFile(path, content) {",
  "  const fs = require(\"fs\");",
  "  fs.writeFileSync(path, content, \"utf8\");",
  "}",
  "// Strip outer quotes (either single or double) if present",
  "function stripQuotes(s) {",
  "  s = s.trim();",
  "  if (s.length >= 2) {",
  "    if ((s[0] === '\"' && s[s.length-1] === '\"') ||",
  "        (s[0] === \"'\" && s[s.length-1] === \"'\")) {",
  "      return s.slice(1, -1);",
  "    }",
  "  }",
  "  return s;",
  "}",
  "function extractCommands(text) {",
  "  const commands = [];",
  "  // Pattern 1: heredoc format for file writing",
  "  // $ write path << EOF ...content... EOF",
  "  const heredocP = /\\$ write ([\\S]+) << ?'?'\"?'?EOF'?\"?'?\\n([\\s\\S]*?)(?:\\nEOF|\\nEOF(?=\\s|$))/g;",
  "  let m;",
  "  while ((m = heredocP.exec(text)) !== null) {",
  "    commands.push({ type: \"write\", path: m[1], content: m[2] });",
  "  }",
  "  // Pattern 2: shell commands in fenced code blocks",
  "  const blockP = /```(?:\\w+)?\\n?([\\s\\S]*?)```/g;",
  "  while ((m = blockP.exec(text)) !== null) {",
  "    const block = m[1];",
  "    const lines = block.split(\"\\n\");",
  "    for (const line of lines) {",
  "      const trimmed = line.trim();",
  "      // Match $ command prefix",
  "      const dollarMatch = trimmed.match(/^\\$ ?(.*)/);",
  "      if (!dollarMatch) continue;",
  "      let cmd = dollarMatch[1].trim();",
  "      // Skip write/heredoc commands (handled above)",
  "      if (cmd.startsWith(\"write \") || cmd.startsWith(\"heredoc\")) continue;",
  "      // Strip \"bash -c \" or \"sh -c \" prefix",
  "      if (cmd.startsWith(\"bash -c \")) cmd = cmd.slice(9);",
  "      else if (cmd.startsWith(\"sh -c \")) cmd = cmd.slice(7);",
  "      // Strip outer quotes",
  "      cmd = stripQuotes(cmd);",
  "      if (!cmd || cmd.includes(\"COMPLETE\") || cmd.length < 3 || cmd.length > 2000) continue;",
  "      commands.push({ type: \"shell\", cmd });",
  "    }",
  "  }",
  "  // Pattern 3: inline backtick commands",
  "  const inlineP = /`\\$ (.*?)`/g;",
  "  while ((m = inlineP.exec(text)) !== null) {",
  "    let cmd = m[1].trim();",
  "    if (cmd.startsWith(\"bash -c \")) cmd = cmd.slice(9);",
  "    else if (cmd.startsWith(\"sh -c \")) cmd = cmd.slice(7);",
  "    cmd = stripQuotes(cmd);",
  "    if (!cmd || cmd.includes(\"COMPLETE\") || cmd.length < 3 || cmd.length > 2000) continue;",
  "    commands.push({ type: \"shell\", cmd });",
  "  }",
  "  return commands;",
  "}",
  "async function chat(prompt, iteration) {",
  "  const iterationNote = iteration > 1 ? \"\\n\\n[Iteration \" + iteration + \"] You have already read files. Now make the actual code changes and commit.\" : \"\";",
  "  const systemPrompt = \"You are a coding agent. You MUST make actual file changes.\" +",
  "    \"\\n\\nFILE WRITES - Use heredoc format:\" +",
  "    \"\\n$ write frontend/path/file.js << EOF\" +",
  "    \"\\n// complete file content\" +",
  "    \"\\nEOF\" +",
  "    \"\\n\\nSHELL - Read files:\" +",
  "    \"\\n$ cat frontend/store/libraryStore.js\" +",
  "    \"\\n$ grep pattern frontend/ -r\" +",
  "    \"\\n\\nSHELL - Commit:\" +",
  "    \"\\n$ git add . && git commit -m \\\"fix: description\\\"\" +",
  "    \"\\n\\nIMPORTANT:\" +",
  "    \"\\n- Use \\\"$ write path << EOF\\\" for all file writes\" +",
  "    \"\\n- Write COMPLETE file content\" +",
  "    \"\\n- Use \\\" for git commit messages (double quotes)\" + iterationNote +",
  "    \"\\n\\nWorking dir: \" + process.cwd();",
  "  const messages = [{ role: \"system\", content: systemPrompt }, { role: \"user\", content: prompt }];",
  "  const stream = await client.chat.completions.create({ model, messages, stream: true, max_tokens: 4096 });",
  "  let response = \"\";",
  "  for await (const event of stream) {",
  "    if (event.choices?.[0]?.delta?.content) response += event.choices[0].delta.content;",
  "  }",
  "  return response;",
  "}",
  "async function main() {",
  "  let prompt = \"\";",
  "  process.stdin.on(\"data\", d => prompt += d);",
  "  process.stdin.on(\"end\", async () => {",
  "    try {",
  "      let done = false, iteration = 0;",
  "      const maxIterations = 20;",
  "      let currentPrompt = prompt;",
  "      while (!done && iteration < maxIterations) {",
  "        iteration++;",
  "        process.stderr.write(\"[ITERATION \" + iteration + \"]\\n\");",
  "        const response = await chat(currentPrompt, iteration);",
  "        process.stderr.write(\"[RESPONSE LEN: \" + response.length + \"]\\n\");",
  "        const cmds = extractCommands(response);",
  "        let commandOutput = \"\";",
  "        for (const item of cmds) {",
  "          if (item.type === \"write\") {",
  "            try {",
  "              writeFile(item.path, item.content);",
  "              commandOutput += \"\\n[WRITTEN] \" + item.path + \" (\" + item.content.length + \" bytes)\\n\";",
  "            } catch (e) {",
  "              commandOutput += \"\\n[WRITE ERROR] \" + item.path + \": \" + e.message + \"\\n\";",
  "            }",
  "          } else if (item.type === \"shell\") {",
  "            process.stderr.write(\"[SHELL] \" + item.cmd.slice(0, 100) + \"\\n\");",
  "            const result = await runShell(item.cmd);",
  "            commandOutput += \"\\n--- Shell: \" + item.cmd.slice(0, 80) + \" ---\\n\";",
  "            commandOutput += result.stdout || \"(no stdout)\";",
  "            if (result.stderr) commandOutput += \"\\nERR: \" + result.stderr;",
  "            commandOutput += \"\\n[exit:\" + result.code + \"]\\n\";",
  "          }",
  "        }",
  "        let outMsg = response;",
  "        if (commandOutput) outMsg += \"\\n\" + commandOutput;",
  "        process.stdout.write(JSON.stringify({ type: \"text\", message: outMsg }) + \"\\n\");",
  "        if (response.includes(\"COMPLETE\")) { done = true; break; }",
  "        if (iteration >= maxIterations) { process.stderr.write(\"[MAX ITER reached]\\n\"); break; }",
  "        currentPrompt = prompt + \"\\n\\n--- Iteration \" + (iteration - 1) + \" ---\\n\" +",
  "          response.substring(Math.max(0, response.length - 2000)) + \"\\n\\n--- Output ---\\n\" +",
  "          commandOutput.substring(Math.max(0, commandOutput.length - 3000)) + \"\\n\\nContinue making fixes. Use \\\"$ write path << EOF\\\" for file writes. Then commit and output <promise>COMPLETE</promise>.\";",
  "      }",
  "      process.stdout.write(\"<promise>COMPLETE</promise>\\n\");",
  "    } catch (err) {",
  "      console.error(\"Error: \" + err.message);",
  "      process.exit(1);",
  "    }",
  "  });",
  "}",
  "main();",
].join("\n");
writeFileSync(scriptPath, scriptContent);

const minimax = () => ({
  name: "minimax",
  env: { NODE_PATH: "/usr/local/lib/node_modules" },
  captureSessions: false,
  buildPrintCommand({ prompt }) {
    return { command: "node .sandcastle/minimax-agent.cjs", stdin: prompt };
  },
  parseStreamLine(line) {
    try {
      const p = JSON.parse(line);
      if (p.type === "text") return [{ type: "text", text: p.message }];
      return [];
    } catch {
      return line.trim() ? [{ type: "text", text: line }] : [];
    }
  },
});

await run({
  agent: minimax(),
  sandbox: docker(),
  promptFile: "./.sandcastle/prompt.md",
});
